---
title: HealthAI working group
timezone: America/Los_Angeles
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
author: Łukasz Kidziński
email: lukasz.kidzinski@gmail.com
description: 'A Site Starter Materialize Templates for Jekyll'
future: true
twitter_username: kidzik
github_username: kidzik
sass:
  style: compressed
