title: HealthAI working group
author: Łukasz Kidziński
email: lukasz.kidzinski@gmail.com
future: true

collections:
  events:
    output: true
  projects:
    output: true
    
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll
twitter_username: kidzik
github_username:  kidzik
timezone: America/Los_Angeles

sass:
    style: compressed
plugins:
- jekyll-avatar